import './globals.css'
import Navigation from './navigation'

export const metadata = {
  title: 'Mohammad Reza Yusufy Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='container'>
        <header className='position-absolute start-0 top-0 w-100'>
          <Navigation/>
        </header>
        <main>{children}</main>
      </body>
    </html>
  )
}
